title: "About me theme for Spress"
description: "Another site creted with Spress"
keywords:
    - drupal
    - php
    - symfony
    - responsive
    - education

author:
    name: socketwench
    headline: "aka, Tess Flynn"
    bio: |
      Drupal developer, speaker, IT educator, recovering Cloud champion
    interests:
        - Drupal
        - Symfony
        - PHP
        - Cloud

# Social networks card
social_networks:
    twitter: socketwench # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: https://github.com/socketwench
    dribbble: # Your iddd
    linkedin: # Your URL
    email: # Your email adress you@yoourDomain.com
    url: deninet.com

texts:
    default_color: "#fff"
    title_color: "#fff"
    headline_color: "#ffa"
    bio_color: "#fff"

background:
    color: "#000"
    image: "css/images/IMG_20141119_135307.jpg "
    size: "2250px"           # global
    size_wide: "1500px"      # resolution 1680
    size_normal: "1300px"    # resolutions < 1280
    size_mobile: "980px"     # resolutions < 786
    size_mobile_p: "980px"   # resolutions < 480

exclude:
    - README.md
    - LICENSE
    - composer.json
